### ISSUE TITLE
Great idea :-)

### ISSUE THREAD

**Issue by petervandenabeele** [pvdb/dotfiles#1]
Maybe you could find some inspiration in my old dot files ...
In the aptly name repo `stuff` (best name ever ?)
https://github.com/petervandenabeele/stuff/tree/master/rc_files

**Comment by pvdb** [comment]
In coding, my metasyntactic variable of choice is `blegga` _(picked it up whilst working in Seattle)_ and at one point, I had a "stuff" repo that - for lack of a better name - I also named `blegga` ... ChezMoi is great, though: I managed to merge two "stuff" repos into a single one, one that's a lot easier to maintain to boot;  highly recommended!
